const $=id=>document.getElementById(id),$$=s=>Array.from(document.querySelectorAll(s));
const TITLES={overview:'PAINEL GERAL',tools:'Ferramentas',settings:'Configurações',queue:'Logs',themes:'Temas',eula:'EULA',guide:'Guia Rápido'};
const THEMES=Array.from({length:36},(_,i)=>{const family=i<26?'base': 'coder';return [`${family}-${String(i%26+1).padStart(2,'0')}`,`hsl(${i*10} 30% 7%)`,`hsl(${i*10} 30% 12% / .85)`,`hsl(${i*10} 90% 65%)`,`hsl(${(i*10+45)%360} 85% 65%)`]});
const PROVIDER_LABELS=['ChatGPT','Claude','Gemini','Grok','Copilot','Perplexity','DeepSeek','Poe','Le Chat','You.com','Meta AI','Qwen','HuggingChat','Character.AI'];
const PROVIDER_RE=/(^|\.)chatgpt\.com$|(^|\.)claude\.ai$|(^|\.)gemini\.google\.com$|(^|\.)copilot\.microsoft\.com$|(^|\.)perplexity\.ai$|(^|\.)grok\.com$|(^|\.)chat\.deepseek\.com$|(^|\.)poe\.com$|(^|\.)chat\.mistral\.ai$|(^|\.)you\.com$|(^|\.)meta\.ai$|(^|\.)chat\.qwen\.ai$|(^|\.)huggingface\.co$|(^|\.)character\.ai$/;
function openTab(id){$$('.tab').forEach(e=>e.classList.toggle('active',e.id===id));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.tab===id));$('pageTitle').textContent=TITLES[id]||'IZGITH';location.hash=id}
$$('.nav').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));
function applyTheme(name){const t=THEMES.find(x=>x[0]===name)||THEMES[0],r=document.documentElement;r.dataset.theme=t[0];r.style.setProperty('--bg',t[1]);r.style.setProperty('--panel',t[2]);r.style.setProperty('--a',t[3]);r.style.setProperty('--b',t[4]);chrome.storage.local.set({theme:t[0]});$$('.theme').forEach(e=>e.classList.toggle('active',e.dataset.theme===t[0]))}
function buildThemeGrid(){const g=$('themeGrid');g.replaceChildren(...THEMES.map(t=>{const b=document.createElement('button');b.className='theme';b.dataset.theme=t[0];b.textContent=t[0].replace(/-/g,' ');b.style.setProperty('--sw1',t[3]);b.style.setProperty('--sw2',t[4]);b.onclick=()=>applyTheme(t[0]);return b}))}
async function renderQueue(){const d=await chrome.storage.local.get({izgithQueue:[]}),q=d.izgithQueue||[];$('statQueue').textContent=q.length;$('dashboardQueue').textContent=q.length?q.map(x=>`${x.name||'item'} · ${x.size||0} B · ${x.kind||'arquivo'}`).join('\n'):'Fila vazia.'}
async function enqueueFiles(files,kind){const existing=(await chrome.storage.local.get({izgithQueue:[]})).izgithQueue||[];const now=Date.now();const additions=files.map((f,i)=>({id:`${now}-${i}-${f.name}`,name:f.name,size:f.size,type:f.type||'',kind,addedAt:new Date().toISOString()}));await chrome.storage.local.set({izgithQueue:existing.concat(additions)});await renderQueue();return additions.length}
function addMessage(who,text){const row=document.createElement('div');row.className='chat-message';row.textContent=`${who}: ${text}`;$('izartMessages').appendChild(row);$('izartMessages').scrollTop=$('izartMessages').scrollHeight}
const ASSISTANT_RULES={IZART:'diagnóstico, auditoria, segurança, CONV-D, SONPEF e ferramentas',Ayella:'orientação de uso do IZGITH, configurações, fluxos e exportação',Júlia:'organização de integrações, KIT_UNICO, fila, temas e operação'};
function reply(name,text){const s=text.toLowerCase();if(s.includes('conv-d')||s.includes('conv d'))return'CONV-D coloca Baixar Conversa nas páginas suportadas e permite Tudo ou Ultima Rodada, com escolha de PDF, Word .doc, TXT, Markdown, JSON ou Excel .xls e escolha do destino.';if(s.includes('sonpef'))return'SONPEF unifica os .ps1 e .py selecionados no navegador, sem Native Messaging. A fila e a saída ficam locais.';if(s.includes('fila'))return'Fila Rápida organiza arquivos locais para processamento posterior. Ela não executa scripts externos por conta própria.';if(s.includes('zip')||s.includes('crx'))return'Selecionar .ZIP/.CRX coloca o pacote na fila para auditoria/extração. É útil antes de instalar uma extensão desconhecida.';if(s.includes('tema')||s.includes('2d')||s.includes('3d')||s.includes('4d'))return'Os 36 temas têm profundidades 2D, 3D e 4D. 2D reduz efeitos, 3D adiciona profundidade/parallax e 4D adiciona movimento temporal.';if(s.includes('host')||s.includes('native'))return'O baseline atual não depende de Native Messaging. O host é opcional e o painel não congela se ele estiver ausente.';if(name==='Ayella')return'Olá! Sou Ayella. '+ASSISTANT_RULES[name]+'. Como posso ajudar?';if(name==='Júlia')return'Olá! Sou Júlia. '+ASSISTANT_RULES[name]+'. Posso orientar a organização do fluxo.';return'Olá! Sou IZART. '+ASSISTANT_RULES[name]+'. Posso ajudar a diagnosticar e organizar o IZGITH.'}
let currentAssistant='IZART';
function openAssistant(name){currentAssistant=name;const chat=$('izartChat');chat.hidden=false;$('assistantChatTitle').textContent=name;$('izartMessages').replaceChildren();addMessage(name,'Olá! Sou '+name+'. Como posso ajudar?');chat.scrollIntoView({behavior:'smooth',block:'nearest'});$('izartInput').focus()}
function setupAssistantArea(){const overview=$('overview'),grid=overview&&overview.querySelector('.assistant-grid'),chat=$('izartChat');if(grid&&chat&&chat.parentElement!==overview)grid.parentElement.appendChild(chat);$$('.assistant-card').forEach(b=>b.onclick=()=>openAssistant(b.dataset.assistant));const legacy=$('toolIzart');if(legacy){const card=legacy.closest('.tool-card');if(card)card.remove()}}
$('assistantClose').onclick=()=>{$('izartChat').hidden=true};$('assistantClear').onclick=()=>{$('izartMessages').replaceChildren();addMessage(currentAssistant,'Conversa limpa.')};$('assistantMin').onclick=()=>{$('izartChat').classList.toggle('chat-minimized')};$('izartSend').onclick=()=>{const i=$('izartInput'),v=i.value.trim();if(!v)return;addMessage('Você',v);setTimeout(()=>addMessage(currentAssistant,reply(currentAssistant,v)),120);i.value='';i.focus()};$('izartInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('izartSend').click()});
async function updateConvDButton(){const s=await chrome.storage.local.get({convDEnabled:true}),on=s.convDEnabled!==false;$('convDStatus').textContent=on?'Ativo':'Desativado';$('toolConvgpt').textContent=on?'Desativar CONV':'Ativar CONV'}
$('toolConvgpt').onclick=async()=>{const s=await chrome.storage.local.get({convDEnabled:true}),on=!(s.convDEnabled!==false);await chrome.storage.local.set({convDEnabled:on});await updateConvDButton();$('hostResult').textContent=on?'CONV-D ativado. O botão Baixar Conversa aparecerá nas conversas suportadas.':'CONV-D desativado. O botão Baixar Conversa ficará oculto.'};
function supportedConversationUrl(raw){try{const u=new URL(raw.trim());return u.protocol==='https:'&&PROVIDER_RE.test(u.hostname)?u:null}catch(_){return null}}
function safeRepositoryUrl(raw){try{const u=new URL(raw.trim());return u.protocol==='https:'&&u.hostname==='github.com'&&/^\/[^/]+\/[^/]+\/?$/.test(u.pathname)?u:null}catch(_){return null}}
$('conversationUrlPrepare').onclick=async()=>{const cu=supportedConversationUrl($('conversationUrl').value),ru=safeRepositoryUrl($('repositoryUrl').value);if(!cu){$('hostResult').textContent='URL da conversa inválida ou plataforma não suportada.';return}if($('repositoryUrl').value.trim()&&!ru){$('hostResult').textContent='Repositório inválido. Use https://github.com/owner/repo.';return}await chrome.tabs.create({url:cu.href,active:true});const target=ru?` Repositório indicado: ${ru.pathname}.`:' ';$('hostResult').textContent='Conversa aberta no contexto autenticado. O CONV-D poderá exportá-la.'+target+' Publicação automática/force-push não é executada pelo módulo.'};
$('downloadByLink').onclick=async()=>{const raw=$('downloadUrl').value.trim();if(!raw){$('hostResult').textContent='Cole uma URL primeiro.';return}const conv=supportedConversationUrl(raw);if(conv){await chrome.tabs.create({url:conv.href,active:true});$('hostResult').textContent='Conversa aberta. Aguarde o carregamento para o botão Baixar Conversa aparecer.';return}try{const u=new URL(raw);if(u.protocol==='http:'||u.protocol==='https:'){const id=await chrome.downloads.download({url:u.href,saveAs:true,conflictAction:'uniquify'});$('hostResult').textContent='Download iniciado. ID '+id+'. Escolha o destino no diálogo do navegador.';return}$('hostResult').textContent='Este módulo trabalha com URLs web HTTP/HTTPS. SMTP/POP não são protocolos de download de arquivos via chrome.downloads e FTP pode ser bloqueado pelo navegador.'}catch(_){$('hostResult').textContent='URL inválida.'}};
$('toolQuickQueue').onclick=()=>$('quickQueueFiles').click();$('quickQueueFiles').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;const n=await enqueueFiles(files,'fila-rapida');$('hostResult').textContent=`Fila Rápida: ${n} arquivo(s) adicionado(s).`;e.target.value=''};
$('toolZipCrx').onclick=()=>$('zipCrxFiles').click();$('zipCrxFiles').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;const valid=files.filter(f=>/\.(zip|crx)$/i.test(f.name));const n=await enqueueFiles(valid,'zip-crx');$('hostResult').textContent=valid.length?`${n} pacote(s) .ZIP/.CRX adicionado(s) à fila.`:'Nenhum .ZIP/.CRX selecionado.';e.target.value=''};
$('toolSonpef').onclick=()=>$('sonpefFiles').click();$('sonpefFiles').onchange=async e=>{const files=[...e.target.files].filter(f=>/\.(ps1|py)$/i.test(f.name));if(!files.length){$('hostResult').textContent='Nenhum .ps1/.py selecionado.';return}const parts=[];for(const f of files)parts.push(`\n===== ${f.name} =====\n`,await f.text());const unified=`# SONPEF UNIFIED · IZGITH\n# Gerado no navegador · ${new Date().toISOString()}\n# Arquivos: ${files.length}\n${parts.join('')}\n`;const u=URL.createObjectURL(new Blob([unified],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='sonpef_unified_izgith.ps1.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('hostResult').textContent=`SONPEF concluído: ${files.length} arquivo(s) unificados.`;e.target.value=''};
$('toolKit').onclick=()=>{$('hostResult').textContent='KIT_UNICO: hub das integrações. As três assistentes ficam na área Assistentes da página inicial.'};$('hostPing').onclick=()=>{$('statHost').textContent='N/A';$('hostResult').textContent='Sistema autônomo verificado: Native Messaging não é requerido.'};$('clearQueue').onclick=async()=>{await chrome.storage.local.set({izgithQueue:[]});renderQueue()};$('randomTheme').onclick=()=>applyTheme(THEMES[Math.floor(Math.random()*THEMES.length)][0]);
$('minimizeDashboard').onclick=async()=>{const tabs=await chrome.tabs.query({active:true,currentWindow:true});const target=tabs.find(t=>t.id!==undefined&&!String(t.url||'').startsWith(chrome.runtime.getURL('')));if(target&&target.id!==undefined)await chrome.tabs.update(target.id,{active:true});const w=await chrome.windows.getCurrent();if(w&&w.id!==undefined)await chrome.windows.remove(w.id)};$('closeDashboard').onclick=async()=>{const w=await chrome.windows.getCurrent();if(w&&w.id!==undefined)await chrome.windows.remove(w.id)};
$('operationMode').onchange=e=>chrome.storage.local.set({operationMode:e.target.value});$('autoMode').onchange=e=>chrome.storage.local.set({autoMode:e.target.value});$('performanceMode').onchange=e=>{document.body.classList.toggle('reduce-motion',e.target.checked);chrome.storage.local.set({performanceMode:e.target.checked})};$('visualDepth').onchange=e=>{document.documentElement.dataset.depth=e.target.value;document.body.dataset.depth=e.target.value;chrome.storage.local.set({visualDepth:e.target.value})};
function enrichSettings(){const panel=$('settings')?.querySelector('.panel');if(!panel||panel.querySelector('.mode-guide'))return;const box=document.createElement('div');box.className='mode-guide';box.innerHTML='<h3>Como funcionam os modos</h3><p><b>Ultra + Controlado — Unificado:</b> combina automação rápida com salvaguardas. O IZGITH prepara tarefas e mantém etapas sensíveis sob controle.</p><p><b>Controlado:</b> prioriza segurança e previsibilidade; ações relevantes aguardam confirmação.</p><p><b>Ultra:</b> prioriza velocidade e automação dentro do navegador.</p><h3>Como funciona o modo automático</h3><p><b>Auto preparar:</b> monta antecipadamente dados, arquivos, parâmetros e sequência sem executar etapa externa.</p><p><b>Auto com confirmação:</b> monta a ação, mostra o que será feito e aguarda confirmação explícita.</p><p><b>Manual:</b> o usuário inicia cada etapa.</p>';panel.appendChild(box)}
(async()=>{buildThemeGrid();const s=await chrome.storage.local.get({theme:'base-01',operationMode:'unified',autoMode:'confirm',performanceMode:false,visualDepth:'3D',convDEnabled:true});applyTheme(s.theme);$('operationMode').value=s.operationMode;$('autoMode').value=s.autoMode;$('performanceMode').checked=!!s.performanceMode;$('visualDepth').value=s.visualDepth;document.documentElement.dataset.depth=s.visualDepth;document.body.dataset.depth=s.visualDepth;document.body.classList.toggle('reduce-motion',!!s.performanceMode);setupAssistantArea();await renderQueue();await updateConvDButton();enrichSettings();openTab(['overview','tools','settings','queue','themes','eula','guide'].includes(location.hash.slice(1))?location.hash.slice(1):'overview');$('splash').classList.add('hidden')})();
