const $=id=>document.getElementById(id);const $$=s=>Array.from(document.querySelectorAll(s));
const TITLES={overview:'Identidade',tools:'Ferramentas',settings:'Configurações',queue:'Logs',themes:'Temas',eula:'EULA',guide:'Guia Rápido'};
const THEMES=Array.from({length:36},(_,i)=>{const family=['cyber','premium','matrix','glass'][Math.floor(i/9)];return [`${family}-${String(i%9+1).padStart(2,'0')}`,`hsl(${i*10} 30% 7%)`,`hsl(${i*10} 30% 12% / .85)`,`hsl(${i*10} 90% 65%)`,`hsl(${(i*10+45)%360} 85% 65%)`];});
function openTab(id){$$('.tab').forEach(e=>e.classList.toggle('active',e.id===id));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.tab===id));$('pageTitle').textContent=TITLES[id]||'IZGITH';location.hash=id;}
$$('.nav').forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));
function applyTheme(name){const t=THEMES.find(x=>x[0]===name)||THEMES[0],r=document.documentElement;r.dataset.theme=t[0];r.style.setProperty('--bg',t[1]);r.style.setProperty('--panel',t[2]);r.style.setProperty('--a',t[3]);r.style.setProperty('--b',t[4]);chrome.storage.local.set({theme:t[0]});$$('.theme').forEach(e=>e.classList.toggle('active',e.dataset.theme===t[0]));}
function buildThemeGrid(){const g=$('themeGrid');g.replaceChildren(...THEMES.map(t=>{const b=document.createElement('button');b.className='theme';b.dataset.theme=t[0];b.textContent=t[0].replace(/-/g,' ');b.style.setProperty('--sw1',t[3]);b.style.setProperty('--sw2',t[4]);b.onclick=()=>applyTheme(t[0]);return b;}));}
async function renderQueue(){const d=await chrome.storage.local.get({izgithQueue:[]}),q=d.izgithQueue||[];$('statQueue').textContent=q.length;$('dashboardQueue').textContent=q.length?q.map(x=>`${x.name||'item'} · ${x.size||0} B`).join('\n'):'Fila vazia.';}
function addMessage(who,text){const row=document.createElement('div');row.className='chat-message';row.textContent=`${who}: ${text}`;$('izartMessages').appendChild(row);$('izartMessages').scrollTop=$('izartMessages').scrollHeight;}
function izartReply(text){const s=text.toLowerCase();if(s.includes('tema'))return 'Posso orientar os 36 temas e as profundidades 2D, 3D e 4D.';if(s.includes('convgpt'))return 'CONVGPT exporta a conversa atual do ChatGPT em PDF, Word, TXT, MD, JSON e Excel.';if(s.includes('sonpef'))return 'SONPEF unifica .ps1 e .py selecionados no navegador, sem PowerShell e sem Native Messaging.';if(s.includes('host'))return 'O baseline autônomo não depende de Native Messaging.';if(s.includes('ayella'))return 'Ayella é o nome canônico da assistente contextual.';return 'IZART online no modo local. Posso explicar ferramentas, temas, modos e diagnóstico do IZGITH.';}
$('toolConvgpt').onclick=async()=>{const tabs=await chrome.tabs.query({active:true,currentWindow:true});const tab=tabs[0];if(!tab||!/^https:\/\/chatgpt\.com\/(c|g|gg)\//.test(tab.url||'')){ $('hostResult').textContent='Abra uma conversa ChatGPT existente; o IZGITH não abrirá uma nova janela.';return;}try{const r=await chrome.tabs.sendMessage(tab.id,{type:'CONVGPT_EXPORT',format:'all'});$('hostResult').textContent=r?.ok?'CONVGPT exportado em todos os formatos.':`CONVGPT: ${r?.error||'falha'}`;}catch(e){$('hostResult').textContent='CONVGPT: recarregue a página da conversa após atualizar a extensão.';}};
$('toolSonpef').onclick=()=>$('sonpefFiles').click();$('sonpefFiles').onchange=async e=>{const files=[...e.target.files].filter(f=>/\.(ps1|py)$/i.test(f.name));if(!files.length){$('hostResult').textContent='Nenhum .ps1/.py selecionado.';return;}const parts=[];for(const f of files)parts.push(`\n===== ${f.name} =====\n`,await f.text());const unified=`# SONPEF UNIFIED · IZGITH\n# Gerado no navegador · ${new Date().toISOString()}\n# Arquivos: ${files.length}\n${parts.join('')}\n`;const u=URL.createObjectURL(new Blob([unified],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='sonpef_unified_izgith.txt';a.click();URL.revokeObjectURL(u);$('hostResult').textContent=`SONPEF concluído: ${files.length} arquivo(s) unificados.`;};
$('toolKit').onclick=()=>{$('hostResult').textContent='KIT_UNICO registrado e disponível como hub de integrações. Nenhum host nativo é necessário.';};$('toolIzart').onclick=()=>{$('izartChat').hidden=false;$('izartInput').focus();if(!$('izartMessages').children.length)addMessage('IZART','Olá! Sou IZART. Como posso ajudar no IZGITH?');};$('izartSend').onclick=()=>{const i=$('izartInput'),v=i.value.trim();if(!v)return;addMessage('Você',v);addMessage('IZART',izartReply(v));i.value='';i.focus();};$('izartInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('izartSend').click();});$('hostPing').onclick=()=>{$('statHost').textContent='N/A';$('hostResult').textContent='Baseline autônomo verificado: Native Messaging não é requerido.';};
$('clearQueue').onclick=async()=>{await chrome.storage.local.set({izgithQueue:[]});renderQueue();};$('randomTheme').onclick=()=>applyTheme(THEMES[Math.floor(Math.random()*THEMES.length)][0]);$('minimizeDashboard').onclick=async()=>{const w=await chrome.windows.getCurrent();await chrome.windows.update(w.id,{state:'minimized'});};$('closeDashboard').onclick=async()=>{const t=await chrome.tabs.getCurrent();if(t?.id!==undefined)await chrome.tabs.remove(t.id);};
$('operationMode').onchange=e=>chrome.storage.local.set({operationMode:e.target.value});$('autoMode').onchange=e=>chrome.storage.local.set({autoMode:e.target.value});$('performanceMode').onchange=e=>{document.body.classList.toggle('reduce-motion',e.target.checked);chrome.storage.local.set({performanceMode:e.target.checked});};$('visualDepth').onchange=e=>{document.documentElement.dataset.depth=e.target.value;chrome.storage.local.set({visualDepth:e.target.value});};
(async()=>{buildThemeGrid();const s=await chrome.storage.local.get({theme:'cyber-01',operationMode:'unified',autoMode:'confirm',performanceMode:false,visualDepth:'3D'});applyTheme(s.theme);$('operationMode').value=s.operationMode;$('autoMode').value=s.autoMode;$('performanceMode').checked=!!s.performanceMode;$('visualDepth').value=s.visualDepth;document.documentElement.dataset.depth=s.visualDepth;document.body.classList.toggle('reduce-motion',!!s.performanceMode);await renderQueue();openTab(TITLES[location.hash.slice(1)]?location.hash.slice(1):'overview');$('splash').classList.add('hidden');})();
