# SONPEF UNIFY - IZGITH integration
# Windows PowerShell 2.0+ compatible. Does not execute discovered scripts.
[CmdletBinding()]
param(
  [string]$BasePath = '',
  [string]$OutputPath = ''
)
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrEmpty($BasePath)) { $BasePath = (Get-Location).Path }
$BasePath = [IO.Path]::GetFullPath($BasePath)
if (-not (Test-Path -LiteralPath $BasePath -PathType Container)) { throw ('Base path not found: ' + $BasePath) }
if ([string]::IsNullOrEmpty($OutputPath)) { $OutputPath = Join-Path $BasePath 'SONPEF_UNIFIED.ps1' }

$files = Get-ChildItem -LiteralPath $BasePath -Recurse -ErrorAction SilentlyContinue | Where-Object {
  $_.PSIsContainer -eq $false -and ($_.Extension -eq '.ps1' -or $_.Extension -eq '.py') -and $_.FullName -ne $OutputPath
}
$header = @(
  '# SONPEF unified inventory generated by IZGITH',
  ('# BasePath: ' + $BasePath),
  ('# Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')), 
  ('# Files: ' + $files.Count),
  '# This file is an inventory container. Python sources are preserved as text and are not executed.',
  ''
)
$parts = New-Object System.Collections.ArrayList
foreach ($f in $files) {
  [void]$parts.Add('')
  [void]$parts.Add(('##### BEGIN FILE: ' + $f.FullName))
  [void]$parts.Add(('# Extension: ' + $f.Extension))
  try {
    $text = [IO.File]::ReadAllText($f.FullName)
    if ($f.Extension -eq '.py') {
      [void]$parts.Add('<# PYTHON SOURCE - TEXT ONLY #>')
      [void]$parts.Add($text)
      [void]$parts.Add('<# END PYTHON SOURCE #>')
    } else {
      [void]$parts.Add($text)
    }
  } catch {
    [void]$parts.Add(('# READ ERROR: ' + $_.Exception.Message))
  }
  [void]$parts.Add(('##### END FILE: ' + $f.FullName))
}
($header + $parts) | Set-Content -LiteralPath $OutputPath -Encoding UTF8 -Force
Write-Output ('SONPEF OK: ' + $files.Count + ' files -> ' + $OutputPath)
