(function(){'use strict';
var BUTTON_ID='izgith-conv-d-export',MENU_ID='izgith-conv-d-menu';
var PROVIDERS=[
{name:'ChatGPT',host:/(^|\.)chatgpt\.com$/i,selectors:['[data-message-author-role]']},
{name:'Claude',host:/(^|\.)claude\.ai$/i,selectors:['[data-testid="user-message"]','[data-testid="assistant-message"]']},
{name:'Gemini',host:/(^|\.)gemini\.google\.com$/i,selectors:['user-query','model-response','message-content']},
{name:'Copilot',host:/(^|\.)copilot\.microsoft\.com$/i,selectors:['[data-message-author-role]','[data-content]']},
{name:'Perplexity',host:/(^|\.)perplexity\.ai$/i,selectors:['[data-testid="conversation-turn"]','[data-message-author-role]']},
{name:'Grok',host:/(^|\.)grok\.com$/i,selectors:['[data-testid="message"]','[data-message-author-role]']},
{name:'DeepSeek',host:/(^|\.)chat\.deepseek\.com$/i,selectors:['[class*="message"]']},
{name:'Poe',host:/(^|\.)poe\.com$/i,selectors:['[data-message-id]']},
{name:'Le Chat',host:/(^|\.)chat\.mistral\.ai$/i,selectors:['[data-message-author-role]','[class*="message"]']},
{name:'You.com',host:/(^|\.)you\.com$/i,selectors:['[data-testid*="message"]','[data-message-author-role]']},
{name:'Meta AI',host:/(^|\.)meta\.ai$/i,selectors:['[data-message-author-role]','[role="article"]']},
{name:'Qwen',host:/(^|\.)chat\.qwen\.ai$/i,selectors:['[data-message-author-role]','[class*="message"]']},
{name:'HuggingChat',host:/(^|\.)huggingface\.co$/i,selectors:['[data-message-author-role]','[class*="message"]']},
{name:'Character.AI',host:/(^|\.)character\.ai$/i,selectors:['[data-message-author-role]','[class*="message"]']}
];
function clean(v){return String(v||'').replace(/\u00a0/g,' ').trim()}function safe(v){return clean(v).replace(/[\\/:*?"<>|]+/g,'_').slice(0,90)||'conversa-ai'}
function provider(){for(var i=0;i<PROVIDERS.length;i++)if(PROVIDERS[i].host.test(location.hostname))return PROVIDERS[i];return{name:location.hostname,selectors:['[data-message-author-role]','article','main [role="article"]']}}
var currentProvider=provider();function enabled(){return window.__IZGITH_CONV_D_ENABLED!==false}function closeMenu(){var m=document.getElementById(MENU_ID);if(m)m.remove()}
function setEnabled(v){window.__IZGITH_CONV_D_ENABLED=!!v;var b=document.getElementById(BUTTON_ID);if(b)b.hidden=!v;if(!v)closeMenu();else mount()}
chrome.storage.local.get({convDEnabled:true},function(s){setEnabled(s.convDEnabled!==false)});chrome.storage.onChanged.addListener(function(c,a){if(a==='local'&&c.convDEnabled)setEnabled(c.convDEnabled.newValue!==false)});
function nodes(){var out=[],seen=[];currentProvider.selectors.forEach(function(sel){Array.prototype.forEach.call(document.querySelectorAll(sel),function(n){if(clean(n.innerText)&&seen.indexOf(n)<0){seen.push(n);out.push(n)}})});out.sort(function(a,b){return a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1});return out}
function attr(n,names){for(var i=0;i<names.length;i++){var v=n.getAttribute(names[i]);if(v)return v}return''}function role(n){var r=(n.getAttribute('data-message-author-role')||'').toLowerCase();if(r)return r;if(n.matches&&n.matches('[data-testid="user-message"]'))return'user';if(n.matches&&n.matches('[data-testid="assistant-message"]'))return'assistant';var s=attr(n,['data-sender','data-author','aria-label']).toLowerCase();if(s.indexOf('user')>=0||s.indexOf('you')>=0||s.indexOf('usuario')>=0)return'user';if(s.indexOf('assistant')>=0||s.indexOf('model')>=0||s.indexOf('ia')>=0)return'assistant';return'unknown'}
function actorId(n){return attr(n,['data-user-id','data-author-id','data-sender-id','data-message-author-id','data-message-id'])}function actor(r){return r==='user'?'Você':r==='assistant'?'IA['+currentProvider.name+']':'Participante'}
function readVisible(store){nodes().forEach(function(n){var text=clean(n.innerText);if(!text)return;var r=role(n),id=actorId(n),key=r+'|'+id+'|'+text;if(!store[key])store[key]={role:r,actor:actor(r),actorId:id||null,text:text}})}
function scroller(){var best=null,area=0;Array.prototype.forEach.call(document.querySelectorAll('body *'),function(e){if(e.scrollHeight>e.clientHeight+300){var r=e.getBoundingClientRect(),a=r.width*r.height;if(a>area){best=e;area=a}}});return best||document.scrollingElement||document.documentElement}function wait(ms){return new Promise(function(r){setTimeout(r,ms)})}
async function collectAll(){var store={},s=scroller(),old=s.scrollTop;s.scrollTop=0;await wait(300);readVisible(store);var stable=0,last=-1;for(var i=0;i<140;i++){readVisible(store);var before=Object.keys(store).length,max=Math.max(0,s.scrollHeight-s.clientHeight);s.scrollTop=Math.min(max,s.scrollTop+Math.max(300,Math.floor(s.clientHeight*.82)));await wait(180);readVisible(store);var after=Object.keys(store).length;if(s.scrollTop>=max){if(after===last)stable++;else stable=0;last=after;if(stable>=4)break}else if(after===before)stable++;else stable=0;if(stable>=10)break}s.scrollTop=old;var messages=Object.keys(store).map(function(k){return store[k]});messages.forEach(function(m,i){m.index=i+1});return{schema:'izgith.conv-d.v4',provider:currentProvider.name,host:location.hostname,title:clean((document.querySelector('h1')||{}).innerText||document.title),url:location.href,exportedAt:new Date().toISOString(),messageCount:messages.length,messages:messages}}
function rounds(d){var out=[],cur=null;d.messages.forEach(function(m){if(m.role==='user'||!cur){cur={number:out.length+1,messages:[]};out.push(cur)}cur.messages.push(m)});return out}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function md(d){return'# '+(d.title||'Conversa AI')+'\n\n- Provedor: '+d.provider+'\n- URL: '+d.url+'\n- Exportado: '+d.exportedAt+'\n- Mensagens: '+d.messageCount+'\n\n'+d.messages.map(function(m){return'## '+m.index+'. '+m.actor+(m.actorId?' (id: '+m.actorId+')':' (id: não exposto pela plataforma)')+'\n\n'+m.text}).join('\n\n---\n\n')+'\n'}
function txt(d){return d.messages.map(function(m){return'['+m.index+'] '+m.actor+(m.actorId?' [id='+m.actorId+']':' [id não exposto]')+'\n'+m.text}).join('\n\n'+'='.repeat(72)+'\n\n')+'\n'}
function html(d){return'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="generator" content="IZGITH CONV-D"></head><body><h1>'+esc(d.title)+'</h1><p>Provedor: '+esc(d.provider)+' | Mensagens: '+d.messageCount+'</p>'+d.messages.map(function(m){return'<article><h2>'+m.index+'. '+esc(m.actor)+(m.actorId?' [id='+esc(m.actorId)+']':' [id não exposto]')+'</h2><pre>'+esc(m.text)+'</pre></article>'}).join('')+'</body></html>'}
function pdf(d){function ascii(v){return String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E\n\r\t]/g,'?')}function p(v){return ascii(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}var lines=[d.title||'Conversa AI','Provedor: '+d.provider,'URL: '+d.url,'Exportado: '+d.exportedAt,'Mensagens: '+d.messageCount,''];d.messages.forEach(function(m){lines.push(m.index+'. '+m.actor+(m.actorId?' [id='+m.actorId+']':' [id nao exposto]'));String(m.text).split(/\r?\n/).forEach(function(x){x=ascii(x);while(x.length>88){lines.push(x.slice(0,88));x=x.slice(88)}lines.push(x||'')});lines.push('')});var pages=[];for(var i=0;i<lines.length;i+=48)pages.push(lines.slice(i,i+48));var objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [] /Count 0 >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'],kids=[];pages.forEach(function(pg,idx){var pn=4+idx*2,cn=pn+1,b='BT\n/F1 9 Tf\n12 TL\n50 750 Td\n';pg.forEach(function(line){b+='('+p(line)+') Tj\nT*\n'});b+='ET';objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents '+cn+' 0 R >>');objs.push('<< /Length '+new TextEncoder().encode(b).length+' >>\nstream\n'+b+'\nendstream');kids.push(pn+' 0 R')});objs[1]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+pages.length+' >>';var out='%PDF-1.4\n',off=[0];objs.forEach(function(o,i){off.push(new TextEncoder().encode(out).length);out+=(i+1)+' 0 obj\n'+o+'\nendobj\n'});var x=new TextEncoder().encode(out).length;out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(var j=1;j<off.length;j++)out+=String(off[j]).padStart(10,'0')+' 00000 n \n';out+='trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+x+'\n%%EOF';return new TextEncoder().encode(out)}
function xls(d){var rows=d.messages.map(function(m){return'<Row><Cell><Data ss:Type="Number">'+m.index+'</Data></Cell><Cell><Data ss:Type="String">'+esc(m.actor)+'</Data></Cell><Cell><Data ss:Type="String">'+esc(m.actorId||'')+'</Data></Cell><Cell><Data ss:Type="String">'+esc(m.text)+'</Data></Cell></Row>'}).join('');return'<?xml version="1.0" encoding="UTF-8"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Conversa"><Table><Row><Cell><Data ss:Type="String">Indice</Data></Cell><Cell><Data ss:Type="String">Participante</Data></Cell><Cell><Data ss:Type="String">ID</Data></Cell><Cell><Data ss:Type="String">Mensagem</Data></Cell></Row>'+rows+'</Table></Worksheet></Workbook>'}
function bytes(v){return v instanceof Uint8Array?v:new TextEncoder().encode(v)}function b64(u){var s='';for(var i=0;i<u.length;i+=0x8000)s+=String.fromCharCode.apply(null,u.subarray(i,i+0x8000));return btoa(s)}function save(name,data,mime){return new Promise(function(resolve,reject){chrome.runtime.sendMessage({type:'SAVE_FILE',filename:name,base64:b64(bytes(data)),mime:mime},function(r){if(chrome.runtime.lastError)reject(new Error(chrome.runtime.lastError.message));else if(!r||!r.ok)reject(new Error(r&&r.error||'Falha ao abrir o diálogo de salvamento.'));else resolve(r)})})}
function exportData(d,f){var ext=f,mime=f==='pdf'?'application/pdf':f==='doc'?'application/msword':f==='txt'?'text/plain;charset=utf-8':f==='md'?'text/markdown;charset=utf-8':f==='json'?'application/json;charset=utf-8':'application/vnd.ms-excel;charset=utf-8',data=f==='pdf'?pdf(d):f==='doc'?html(d):f==='txt'?txt(d):f==='md'?md(d):f==='json'?JSON.stringify(d,null,2):xls(d);return save(safe(d.title)+'.'+ext,data,mime)}
function showMenu(){closeMenu();var m=document.createElement('div');m.id=MENU_ID;m.innerHTML='<div class="izgith-cd-head"><span class="izgith-cd-title">CONV-D · Exportar conversa</span><span><button type="button" id="izgith-cd-x" aria-label="Fechar">×</button></span></div><div class="izgith-cd-info">Escolha o escopo e o formato. O navegador abrirá o diálogo para você escolher onde salvar.</div><label>Escopo<select id="izgith-cd-scope"><option value="all">Tudo</option><option value="round">Ultima Rodada</option></select></label><label>Formato<select id="izgith-cd-format"><option value="pdf">📄 PDF</option><option value="doc">📝 Word .doc</option><option value="txt">📃 TXT</option><option value="md">📘 Markdown .md</option><option value="json">🧩 JSON estruturado</option><option value="xls">📊 Excel .xls</option></select></label><button type="button" id="izgith-cd-go">Baixar</button><button type="button" class="izgith-cd-cancel">Cancelar</button>';document.body.appendChild(m);m.querySelector('#izgith-cd-x').onclick=closeMenu;m.querySelector('.izgith-cd-cancel').onclick=closeMenu;m.addEventListener('click',async function(e){if(e.target.id!=='izgith-cd-go')return;var scope=m.querySelector('#izgith-cd-scope').value,format=m.querySelector('#izgith-cd-format').value,b=e.target;try{b.disabled=true;b.textContent='Lendo conversa…';var d=await collectAll();if(!d.messages.length)throw new Error('Nenhuma mensagem detectada em '+d.provider+'.');if(scope==='round'){var rs=rounds(d),chosen=rs[rs.length-1];d=Object.assign({},d,{scope:'last_round',round:chosen.number,messageCount:chosen.messages.length,messages:chosen.messages})}else d.scope='all';b.textContent='Abrindo salvar…';await exportData(d,format);closeMenu()}catch(err){console.error('[IZGITH CONV-D]',err);b.disabled=false;b.textContent='Tentar novamente';m.querySelector('.izgith-cd-info').textContent='Erro: '+err.message}})}
function mount(){if(!enabled()||!document.body||document.getElementById(BUTTON_ID))return;var b=document.createElement('button');b.id=BUTTON_ID;b.type='button';b.textContent='Baixar Conversa';b.title='Exportar Tudo ou Ultima Rodada';b.addEventListener('click',showMenu);document.body.appendChild(b)}mount();new MutationObserver(function(){mount()}).observe(document.documentElement,{childList:true,subtree:true});
})();
