(() => {
  'use strict';
  const BUTTON_ID='izgith-convgpt-export', MENU_ID='izgith-convgpt-menu', FORMATS=['pdf','doc','txt','md','json','xls'];
  const clean=v=>String(v||'').replace(/\u00a0/g,' ').trim();
  const safeName=v=>clean(v).replace(/[\\/:*?"<>|]+/g,'_').slice(0,90)||'conversa-chatgpt';
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function collect(){const nodes=[...document.querySelectorAll('[data-message-author-role]')];const messages=nodes.map((node,index)=>({index:index+1,role:node.getAttribute('data-message-author-role')||'unknown',text:clean(node.innerText)})).filter(m=>m.text);return {schema:'izgith.convgpt.v2',title:clean(document.querySelector('h1')?.innerText||document.title.replace(/\s*[-|]\s*ChatGPT.*$/i,'')),url:location.href,exportedAt:new Date().toISOString(),messageCount:messages.length,messages};}
  async function collectCurrentConversation(){const y=window.scrollY;let last=-1,stable=0;for(let i=0;i<24;i++){const count=document.querySelectorAll('[data-message-author-role]').length;if(count===last)stable++;else stable=0;last=count;window.scrollTo(0,document.body.scrollHeight);await sleep(160);window.scrollTo(0,0);await sleep(160);if(stable>=2)break;}const data=collect();window.scrollTo(0,y);return data;}
  function markdown(d){return `# ${d.title||'Conversa ChatGPT'}\n\n- URL: ${d.url}\n- Exportado: ${d.exportedAt}\n- Mensagens: ${d.messageCount}\n\n${d.messages.map(m=>`## ${m.index}. ${m.role}\n\n${m.text}`).join('\n\n---\n\n')}\n`;}
  function text(d){return d.messages.map(m=>`[${m.index}] ${m.role}\n${m.text}`).join('\n\n'+'='.repeat(72)+'\n\n')+'\n';}
  function html(d){const e=v=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${e(d.title)}</title><style>body{font-family:Arial;margin:40px;line-height:1.45}article{break-inside:avoid;border-bottom:1px solid #ccc;padding:12px 0}pre{white-space:pre-wrap;font:inherit}</style></head><body><h1>${e(d.title||'Conversa ChatGPT')}</h1><p>${d.messageCount} mensagens · ${e(d.exportedAt)}</p>${d.messages.map(m=>`<article><h2>${m.index}. ${e(m.role)}</h2><pre>${e(m.text)}</pre></article>`).join('')}</body></html>`;}
  function pdfBytes(d){const n=v=>String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E\xA0-\xFF]/g,'?'),e=v=>n(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');const lines=[d.title||'Conversa ChatGPT',`URL: ${d.url}`,`Exportado: ${d.exportedAt}`,`Mensagens: ${d.messageCount}`,''];for(const m of d.messages){lines.push(`${m.index}. ${m.role}`);for(const raw of String(m.text).split(/\r?\n/)){let s=raw||' ';while(s.length>92){lines.push(s.slice(0,92));s=s.slice(92);}lines.push(s);}lines.push('');}const pages=[];for(let i=0;i<lines.length;i+=52)pages.push(lines.slice(i,i+52));const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids ['+pages.map((_,i)=>`${4+i*2} 0 R`).join(' ')+`] /Count ${pages.length} >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'];for(let i=0;i<pages.length;i++){const p=4+i*2,c=p+1,content=['BT','/F1 9 Tf','12 TL','50 750 Td',...pages[i].map((line,j)=>`(${e(line)}) Tj ${j===pages[i].length-1?'':'T*'}`),'ET'].join('\n');objects[p-1]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${c} 0 R >>`;objects[c-1]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`;}let pdf='%PDF-1.4\n%\xFF\xFF\n',off=[0];for(let i=0;i<objects.length;i++){off[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const x=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<off.length;i++)pdf+=`${String(off[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return new TextEncoder().encode(pdf);}
  function excel(d){const e=v=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Conversa"><Table><Row><Cell><Data ss:Type="String">Indice</Data></Cell><Cell><Data ss:Type="String">Papel</Data></Cell><Cell><Data ss:Type="String">Mensagem</Data></Cell></Row>${d.messages.map(m=>`<Row><Cell><Data ss:Type="Number">${m.index}</Data></Cell><Cell><Data ss:Type="String">${e(m.role)}</Data></Cell><Cell><Data ss:Type="String">${e(m.text)}</Data></Cell></Row>`).join('')}</Table></Worksheet></Workbook>`;}
  function download(name,c,type){const u=URL.createObjectURL(new Blob([c],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
  function exportOne(d,f){const b=safeName(d.title);if(f==='md')return download(`${b}.md`,markdown(d),'text/markdown;charset=utf-8');if(f==='txt')return download(`${b}.txt`,text(d),'text/plain;charset=utf-8');if(f==='json')return download(`${b}.json`,JSON.stringify(d,null,2),'application/json;charset=utf-8');if(f==='doc')return download(`${b}.doc`,html(d),'application/msword;charset=utf-8');if(f==='xls')return download(`${b}.xls`,excel(d),'application/vnd.ms-excel;charset=utf-8');if(f==='pdf')return download(`${b}.pdf`,pdfBytes(d),'application/pdf');throw new Error(`Formato não suportado: ${f}`);}
  async function exportConversation(format='all'){const b=document.getElementById(BUTTON_ID);if(b){b.disabled=true;b.textContent='Exportando…';}try{const d=await collectCurrentConversation();if(!d.messages.length)throw new Error('Nenhuma mensagem carregada nesta conversa.');for(const f of(format==='all'?FORMATS:[format]))exportOne(d,f);if(b)b.textContent=`CONVGPT ✓ ${d.messageCount} mensagens`;}catch(e){if(b)b.textContent=`CONVGPT: ${e.message}`;console.error('[IZGITH CONVGPT]',e);}finally{setTimeout(()=>{if(b){b.disabled=false;b.textContent='Baixar conversa · CONVGPT';}},3500);}}
  function mount(){if(document.getElementById(BUTTON_ID))return;const w=document.createElement('div');w.id=MENU_ID;const b=document.createElement('button');b.id=BUTTON_ID;b.type='button';b.textContent='Baixar conversa · CONVGPT';const menu=document.createElement('div');menu.hidden=true;for(const f of[...FORMATS,'all']){const item=document.createElement('button');item.type='button';item.textContent=f==='all'?'Baixar todos os formatos':`Baixar .${f}`;item.addEventListener('click',()=>{menu.hidden=true;exportConversation(f);});menu.appendChild(item);}b.addEventListener('click',()=>{menu.hidden=!menu.hidden;});w.append(b,menu);document.body.appendChild(w);}
  chrome.runtime.onMessage.addListener((m,_s,sendResponse)=>{if(m?.type!=='CONVGPT_EXPORT')return;exportConversation(m.format||'all').then(()=>sendResponse({ok:true})).catch(e=>sendResponse({ok:false,error:e.message}));return true;});
  mount();new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});
})();
