(() => {
  'use strict';
  const PROFILE_KEY='izgith.enshrouded.profiles';
  const STATE_KEY='izgith.enshrouded.manager.state';
  const ACTIONS=['verify','install','start','stop','backup','restore','prune','mods','resources','version'];
  const $=id=>document.getElementById(id);
  const loadProfiles=async()=>{const s=await chrome.storage.local.get({[PROFILE_KEY]:[]});return Array.isArray(s[PROFILE_KEY])?s[PROFILE_KEY]:[]};
  const saveProfiles=p=>chrome.storage.local.set({[PROFILE_KEY]:p});
  function normalizeProfile(profile){return{id:profile.id||crypto.randomUUID(),name:String(profile.name||'Servidor Enshrouded').trim()||'Servidor Enshrouded',host:String(profile.host||'').trim(),port:Number(profile.port)||15636,notes:String(profile.notes||'').trim(),version:String(profile.version||'latest').trim()||'latest',backupCron:String(profile.backupCron||'*/60 * * * *').trim(),backupFormat:String(profile.backupFormat||'zstd').trim(),backupKeepLast:Number.isInteger(Number(profile.backupKeepLast))?Number(profile.backupKeepLast):24,modsEnabled:profile.modsEnabled!==false,resourcePollInterval:Number(profile.resourcePollInterval)||60,updatedAt:new Date().toISOString()}}
  function validate(profile){const host=String(profile.host||'').trim(),port=Number(profile.port);const hostOk=/^(?=.{1,253}$)[a-zA-Z0-9.-]+$/.test(host)||/^\[[0-9a-fA-F:]+\]$/.test(host);const portOk=Number.isInteger(port)&&port>=1&&port<=65535;return{ok:hostOk&&portOk,host,port,errors:[].concat(hostOk?[]:['host inválido']).concat(portOk?[]:['porta deve ser 1–65535'])}}
  async function upsert(profile){const item=normalizeProfile(profile),v=validate(item);if(!v.ok)throw new Error(v.errors.join('; '));const p=await loadProfiles(),i=p.findIndex(x=>x.id===item.id);if(i>=0)p[i]=item;else p.unshift(item);await saveProfiles(p);return item}
  const remove=async id=>saveProfiles((await loadProfiles()).filter(x=>x.id!==id));
  const address=p=>`${p.host}:${p.port||15636}`;
  function config(profile){const p=normalizeProfile(profile);return{ENSHROUDED_NAME:p.name,ENSHROUDED_QUERY_PORT:15637,VERSION:p.version,BACKUP_CRON:p.backupCron,BACKUP_FORMAT:p.backupFormat,BACKUP_KEEP_LAST:p.backupKeepLast,BACKUP_LIVE:true,BACKUP_COLD:true,BACKUP_EMERGENCY:true,RESOURCE_POLL_INTERVAL:p.resourcePollInterval,LOG_TAIL:false,MODS_ENABLED:p.modsEnabled}}
  function compose(profile){const c=config(profile);return['services:','  enshrouded:','    image: ghcr.io/lincolnthalles/enshrouded-container:latest','    restart: unless-stopped','    environment:',...Object.entries(c).map(([k,v])=>`      ${k}: ${JSON.stringify(v)}`),'    volumes:','      - ./data/manifests:/data/manifests','      - ./data/wineprefix:/data/wineprefix','      - ./data/mods:/data/mods','      - ./data/saves:/data/saves','      - ./data/backups:/data/backups','      - ./data/config:/data/config','      - ./data/logs:/data/logs','    ports:','      - "15636:15636/udp"','      - "15637:15637/udp"','      - "27015:27015/tcp"','      - "27015:27015/udp"'].join('\n')+'\n'}
  function plan(profile,action){const p=normalizeProfile(profile);if(!ACTIONS.includes(action))throw new Error('Ação Enshrouded não suportada.');const common={verify:['validar endpoint e parâmetros','verificar configuração e diretórios'],install:['validar versão','preparar diretórios de manifests','preparar configuração'],start:['validar configuração','verificar portas 15636/15637/27015','preparar inicialização'],stop:['preparar encerramento gracioso','programar backup cold'],backup:['preparar backup live/cold','aplicar retenção','registrar destino'],restore:['selecionar backup','validar integridade do pacote','preparar restauração'],prune:['calcular retenção','selecionar backups antigos','preparar remoção'],mods:['validar diretório de mods','preparar overlay','verificar DLL override quando aplicável'],resources:['configurar polling de CPU/RSS','registrar intervalo','preparar relatório'],version:['consultar versão desejada','registrar manifest/build','preparar atualização determinística']};return{schema:'izgith.enshrouded.plan.v1',action,profile:p,generatedAt:new Date().toISOString(),source:'ENSHROUDED MANAGER / enshrouded-container aligned',execution:'browser-plan-only',externalProcessStarted:false,steps:common[action].map((description,i)=>({order:i+1,description,status:'prepared'}))}}
  const persist=async patch=>{const s=await chrome.storage.local.get({[STATE_KEY]:{}});await chrome.storage.local.set({[STATE_KEY]:{...(s[STATE_KEY]||{}),...patch,updatedAt:new Date().toISOString()}})};
  window.IZGITHEnshrouded={list:loadProfiles,upsert,remove,validate,address,actions:ACTIONS.slice(),config,compose,plan,async prepare(profile,action){const p=plan(profile,action);await persist({lastAction:action,lastPlan:p});return p},async getState(){const s=await chrome.storage.local.get({[STATE_KEY]:{}});return s[STATE_KEY]||{}}};
  const svg=(d,fill='none')=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="${fill}">${d}</svg>`;
  const bookmark=()=>svg('<path d="M6 4h12v16l-6-3-6 3z"></path>','currentColor');
  const power=()=>svg('<path d="M12 2v10"></path><path d="M6.2 5.5a8 8 0 1 0 11.6 0"></path>');
  const menu=()=>svg('<path d="M4 6h16M4 12h16M4 18h16"></path>');
  const replaceButton=(b,content,title)=>{if(!b)return null;const n=b.cloneNode(false);n.innerHTML=content;n.title=title;n.setAttribute('aria-label',title);b.replaceWith(n);return n};
  function patchToolMenus(){
    const conv=$('providerMenuButton');if(conv&&!conv.dataset.hardened){conv.dataset.hardened='1';const n=replaceButton(conv,menu(),'Plataformas suportadas');n.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const m=$('providerMenu');if(!m)return;const open=m.hidden;m.hidden=!open;n.setAttribute('aria-expanded',String(open))})}
    const gh=$('githubMenuButton'),gm=$('githubMenu');if(gh&&gm&&!gh.dataset.hardened){gh.dataset.hardened='1';const n=replaceButton(gh,menu(),'MENU DE AÇÕES DO UPPER GITHUB');['githubFiles','githubFolders','githubCheck','githubConfig'].forEach(id=>{if($(id))$(id).hidden=true});n.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=gm.hidden;gm.hidden=!open;n.setAttribute('aria-expanded',String(open))});gm.replaceChildren(...[['githubFiles','ARQUIVOS'],['githubFolders','PASTAS'],['githubCheck','CHECK HOST/GIT'],['githubConfig','DOWNLOAD CONFIG HOST']].map(([id,label],i)=>{const row=document.createElement('button');row.type='button';row.className='provider-row upper-menu-action';row.style.cssText=`display:flex;width:100%;border:0;background:transparent;text-align:left;align-items:center;gap:6px;padding:6px;color:inherit;--mark:hsl(${i*85} 85% 60%)`;const mark=document.createElement('span');mark.className='bookmark';mark.innerHTML=bookmark();const text=document.createElement('span');text.textContent=label;row.append(mark,text);row.addEventListener('click',()=>$(id)?.click());return row}))}
    const cp=$('toolConvgpt'),cs=$('convDStatus');if(cp&&!cp.dataset.hardened){const n=replaceButton(cp,power(),'Ativar ou desativar CONV-D');n.id='toolConvgpt';n.dataset.hardened='1';n.addEventListener('click',async()=>{const s=await chrome.storage.local.get({convDEnabled:true}),on=s.convDEnabled===false;await chrome.storage.local.set({convDEnabled:on});if(cs)cs.textContent=on?'Ativo':'OFF';n.title=on?'Desativar CONV-D':'Ativar CONV-D'})}
    const up=$('toggleForceSync'),us=$('forceSyncStatus');if(up&&!up.dataset.hardened){const n=replaceButton(up,power(),'Ativar ou desativar UPPER URL');n.id='toggleForceSync';n.dataset.hardened='1';n.addEventListener('click',async()=>{const s=await chrome.storage.local.get({forceSync:false}),on=!s.forceSync;await chrome.storage.local.set({forceSync:on});if(us)us.textContent=on?'ON':'OFF'})}
    document.querySelectorAll('.tool-card').forEach(c=>{c.style.minHeight='68px';c.style.height='auto';c.style.padding='9px'});
  }
  function patchServerPanel(){
    const panel=document.querySelector('#servers .panel');if(!panel||panel.dataset.enshroudedHardened)return;panel.dataset.enshroudedHardened='1';
    const badge=panel.querySelector('.section-head .badge');if(badge){const open=document.createElement('button');open.type='button';open.className='icon-action compact enshrouded-open';open.title='Abrir ENSHROUDED MANAGER em nova tela';open.setAttribute('aria-label','Abrir ENSHROUDED MANAGER em nova tela');open.innerHTML=svg('<rect x="5" y="5" width="14" height="14" rx="1"></rect><path d="M14 5h5v5M19 5l-8 8"></path>');open.addEventListener('click',()=>chrome.tabs.create({url:chrome.runtime.getURL('ui/enshrouded.html'),active:true}));badge.insertAdjacentElement('afterend',open)}
    const box=document.createElement('div');box.className='enshrouded-manager-actions';const actions=[['verify','Verificar'],['install','Preparar Instalação'],['start','Preparar Início'],['stop','Preparar Parada'],['backup','Backup'],['restore','Restaurar'],['prune','Retenção'],['mods','Mods'],['resources','Recursos'],['version','Versão']];actions.forEach(([a,label])=>{const b=document.createElement('button');b.className='btn ghost';b.type='button';b.textContent=label;b.title=`Preparar ação ${label} sem iniciar processo externo`;b.onclick=async()=>{const p={name:$('serverName')?.value,host:$('serverHost')?.value,port:$('serverPort')?.value,notes:$('serverNotes')?.value},v=validate(p);if(!v.ok){$('hostResult').textContent='Informe host e porta válidos antes de preparar a ação.';return}try{const r=await window.IZGITHEnshrouded.prepare(p,a);$('hostResult').textContent=`ENSHROUDED MANAGER: ${label} preparado (${r.steps.length} etapa(s)); nenhum processo externo foi iniciado.`}catch(e){$('hostResult').textContent='Falha: '+e.message}};box.appendChild(b)});panel.insertBefore(box,$('serverList'));
    const exp=document.createElement('div');exp.style.cssText='display:flex;gap:6px;flex-wrap:wrap;margin:6px 0';[['config','Baixar Config'],['compose','Baixar Compose'],['plan','Baixar Plano']].forEach(([kind,label])=>{const b=document.createElement('button');b.className='btn';b.type='button';b.textContent=label;b.onclick=()=>{const p={name:$('serverName')?.value,host:$('serverHost')?.value,port:$('serverPort')?.value,notes:$('serverNotes')?.value},v=validate(p);if(!v.ok){$('hostResult').textContent='Informe host e porta válidos.';return}let content,filename,mime;if(kind==='config'){content=JSON.stringify(config(p),null,2);filename='enshrouded-server-config.json';mime='application/json'}else if(kind==='compose'){content=compose(p);filename='docker-compose.enshrouded.yml';mime='text/yaml'}else{content=JSON.stringify(plan(p,'verify'),null,2);filename='enshrouded-manager-plan.json';mime='application/json'}const u=URL.createObjectURL(new Blob([content],{type:mime})),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('hostResult').textContent=`${label} gerado localmente.`};exp.appendChild(b)});panel.insertBefore(exp,box);
  }
  function patchWhenReady(){patchToolMenus();patchServerPanel();$('splash')?.classList.add('hidden')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchWhenReady,{once:true});else patchWhenReady();
})();