#!/usr/bin/env python3
from __future__ import annotations
import json, re, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; EXT=ROOT/'extension'; checks=[]
def check(label,condition,detail=''):
    ok=bool(condition); checks.append(ok); print(f'[{len(checks):02d}] {label:.<34} {"OK" if ok else "FALHA"} {detail}')
    if not ok: raise SystemExit(1)
def read_json(path):
    try:return json.loads(path.read_text(encoding='utf-8'))
    except Exception as exc: print(f'JSON parse {path}: {exc}'); return None
def main():
    check('pasta raiz',ROOT.is_dir()); rp=ROOT/'manifest.json'; rm=read_json(rp) if rp.is_file() else None; check('manifest.json raiz',rp.is_file()); check('JSON Manifest V3 raiz',isinstance(rm,dict) and rm.get('manifest_version')==3)
    if isinstance(rm,dict):
        rw=rm.get('background',{}).get('service_worker'); rpop=rm.get('action',{}).get('default_popup'); ri=list(rm.get('icons',{}).values()); check('SW raiz declarado',isinstance(rw,str) and bool(rw)); check('SW raiz existe',bool(rw) and (ROOT/rw).is_file()); check('popup raiz existe',bool(rpop) and (ROOT/rpop).is_file()); check('icones raiz existem',bool(ri) and all((ROOT/x).is_file() for x in ri))
    mp=EXT/'manifest.json'; check('manifest.json extensao',mp.is_file()); m=read_json(mp); check('JSON Manifest V3 válido',isinstance(m,dict) and m.get('manifest_version')==3)
    if isinstance(rm,dict) and isinstance(m,dict): check('manifest raiz sincronizado',rm.get('version')==m.get('version'))
    wr=m.get('background',{}).get('service_worker') if isinstance(m,dict) else None; worker=EXT/wr if wr else EXT/'missing'; check('background/service worker declarado',isinstance(wr,str) and bool(wr)); check('background/service worker existe',worker.is_file()); check('service worker nao vazio',worker.is_file() and worker.stat().st_size>0)
    js=list(EXT.rglob('*.js'))
    try: node=subprocess.run(['node','--version'],capture_output=True,text=True,timeout=10)
    except Exception: node=None
    if js and node and node.returncode==0: check('JavaScript syntax',all(subprocess.run(['node','--check',str(p)],capture_output=True).returncode==0 for p in js))
    else: check('JavaScript encontrado',bool(js))
    html=list(EXT.rglob('*.html')); css=list(EXT.rglob('*.css')); check('HTML',bool(html)); check('CSS',bool(css) and all((lambda t:t.count('{')==t.count('}'))(p.read_text(encoding='utf-8')) for p in css))
    for size in (16,32,48,128): check(f'icon{size}.png',(EXT/f'assets/icons/icon{size}.png').is_file() and (EXT/f'assets/icons/icon{size}.png').stat().st_size>0)
    refs=[m.get('action',{}).get('default_popup',''),wr or '',*m.get('icons',{}).values()]; check('referências de arquivos',all((EXT/x).is_file() for x in refs if x))
    themes=read_json(EXT/'themes/catalog.json'); fam=themes.get('families',{}) if isinstance(themes,dict) else {}; check('36 temas',isinstance(themes,dict) and themes.get('total')==36 and sum(map(len,fam.values()))==36)
    dash=(EXT/'ui/dashboard.html').read_text(encoding='utf-8'); djs=(EXT/'ui/dashboard.js').read_text(encoding='utf-8'); mf=EXT/'ui/menu-fix.js'; mft=mf.read_text(encoding='utf-8') if mf.is_file() else ''
    check('EULA','EULA' in dash or (ROOT/'docs/EULA.md').is_file()); check('Guia Rápido','Guia Rápido' in dash or (ROOT/'docs/GUIA_RAPIDO.md').is_file()); check('SONPEF',(ROOT/'integrations/SONPEF/integration.json').is_file()); check('CONV-D',(ROOT/'integrations/CONV-D/integration.json').is_file()); check('KIT_UNICO',(ROOT/'integrations/KIT_UNICO/integration.json').is_file()); check('Servidores','data-tab="servers"' in dash and '<section class="tab" id="servers">' in dash)
    em=read_json(ROOT/'integrations/ENSHROUDED_MANAGER/integration.json'); check('ENSHROUDED MANAGER',isinstance(em,dict) and (EXT/'integrations/enshrouded-manager.js').is_file()); check('ENSHROUDED sem executor externo',isinstance(em,dict) and em.get('external_process') is False and em.get('docker_execution') is False and em.get('native_messaging') is False)
    emui=EXT/'ui/enshrouded.html'; emcss=EXT/'ui/enshrouded-manager.css'; emjs=EXT/'ui/enshrouded-manager-screen.js'; rc=ROOT/'integrations/ENSHROUDED_MANAGER/runtime-contract.json'; check('ENSHROUDED UI v2',emui.is_file() and emcss.is_file() and emjs.is_file()); check('ENSHROUDED runtime contract',rc.is_file() and read_json(rc).get('browser_execution') is False)
    conv=EXT/'integrations/conv-d.js'; ct=conv.read_text(encoding='utf-8') if conv.is_file() else ''; wt=worker.read_text(encoding='utf-8'); required=['izgith.conv-d.v4','ChatGPT','Claude','Gemini','pdf','doc','txt','md','json','xls','Baixar Conversa','Tudo','Ultima Rodada','SAVE_FILE','convDEnabled']; check('CONV-D export contract',all(x in ct for x in required) and 'saveAs:true' in wt)
    reg=read_json(ROOT/'integrations/assistant_registry.json'); names=[x.get('name') for x in reg.get('canonical_assistants',[]) if isinstance(x,dict)] if isinstance(reg,dict) else []; check('IA/assistentes',names==['Júlia','Ayella','IZART']); check('service worker sem alias proibido',not any(x in wt for x in ('Ayelle','alias Ayella','Alias: Ayella'))); check('registry IA canônico',isinstance(reg,dict) and reg.get('naming_policy',{}).get('ayella_is_alias') is False); check('registry sem aliases proibidos',not any(x in names for x in ('Ayelle','alias Ayella','Alias: Ayella')))
    mv=str(m.get('version','')); pv=str((read_json(ROOT/'package.json') or {}).get('version','')); mm=re.fullmatch(r'(\d+\.\d+\.\d+)\.(\d+)',mv); expected=f'{mm.group(1)}-{int(mm.group(2)):05d}' if mm else ''; expected_registry=f'{mm.group(1)}.{int(mm.group(2)):05d}' if mm else ''; check('versões sincronizadas',bool(mm) and pv==expected); check('versão registry sincronizada',isinstance(reg,dict) and reg.get('version')==expected_registry)
    perms=m.get('permissions',[]); check('baseline sem Native Messaging','nativeMessaging' not in perms); check('CONV-D sem botão abrir','Abrir CONV-D' not in dash and 'Abrir CONVGPT' not in dash and 'Abrir ChatGPT' not in dash); check('SONPEF autônomo','sonpefFiles' in dash and 'Selecionar scripts' in dash); check('IZART interativo','izartChat' in dash and 'izartSend' in dash); check('assistentes na inicial','assistant-grid' in dash and all(x in dash for x in ['IZART','Ayella','Júlia'])); check('configurações documentadas',all(x in dash for x in ['Ultra + Controlado — Unificado','Controlado','Ultra','Auto preparar','Auto com confirmação','Manual'])); check('profundidade funcional',all(x in dash for x in ['2D','3D','4D']) and 'data-depth' in dash); check('UPPER GITHUB menu','githubMenuButton' in dash and 'githubMenu' in dash and 'upper-github-menu' in dash); check('UPPER GITHUB power','githubPower' in dash and 'upperGithubEnabled' in djs); check('UPPER URL power','toggleForceSync' in dash and 'forceSyncStatus' in dash and 'power-action' in dash); check('CONV-D menu','providerMenuButton' in dash and 'providerMenu' in dash); dc=(EXT/'ui/dashboard.css').read_text(encoding='utf-8'); check('menus ancorados','position:relative' in dc and 'upper-github-menu' in dc); check('menu controller robusto',mf.is_file() and 'stopImmediatePropagation' in mft and "['githubMenuButton', 'githubMenu']" in mft and "['providerMenuButton', 'providerMenu']" in mft); check('menu controller empacotado','menu-fix.js' in dash); check('window controls','minimizeDashboard' in dash and 'closeDashboard' in dash and 'chrome.windows.update' in djs and 'chrome.windows.remove' in djs); check('documentação 00066',(ROOT/'docs/CHANGELOG_00066.md').is_file() and (ROOT/'docs/GUIA_RAPIDO.md').is_file() and (ROOT/'docs/EULA.md').is_file())
    providers=read_json(ROOT/'integrations/CONV-D/integration.json').get('providers',[]); check('CONV-D providers',len(providers)>=10 and 'ChatGPT' in providers and 'Claude' in providers); print('BUILD PASS'); return 0
if __name__=='__main__': raise SystemExit(main())
